#include <instructions.h>
#include <cpu.h>

instruction instructions[0x100] = {
    //0x0X
    [0x00] = {IN_NOP, AM_IMP},
    [0x01] = {IN_LD, AM_R_D16, RG_BC},
    [0x02] = {IN_LD, AM_MR_R, RG_BC, RG_A},
    [0x03] = {IN_INC, AM_R, RG_BC},
    [0x04] = {IN_INC, AM_R, RG_B},
    [0x05] = {IN_DEC, AM_R, RG_B},
    [0x06] = {IN_LD, AM_R_D8, RG_B},

    [0x08] = {IN_LD, AM_A16_R, RG_NONE, RG_SP},
 
    [0x0A] = {IN_LD, AM_R_MR, RG_A, RG_BC},
    [0x0B] = {IN_DEC, AM_R, RG_BC},
    [0x0C] = {IN_INC, AM_R, RG_C},
    [0x0D] = {IN_DEC, AM_R, RG_C},
    [0x0E] = {IN_LD, AM_R_D8, RG_C},

    //0x1X
    [0x11] = {IN_LD, AM_R_D16, RG_DE},
    [0x12] = {IN_LD, AM_MR_R, RG_DE, RG_A},
    [0x13] = {IN_INC, AM_R, RG_DE},
    [0x14] = {IN_INC, AM_R, RG_D},
    [0x15] = {IN_DEC, AM_R, RG_D},
    [0x16] = {IN_LD, AM_R_D8, RG_D},
    [0x18] = {IN_JR, AM_D8}, 
    [0x1A] = {IN_LD, AM_R_MR, RG_A, RG_DE},
    [0x1B] = {IN_DEC, AM_R, RG_DE},
    [0x1C] = {IN_INC, AM_R, RG_E},
    [0x1D] = {IN_DEC, AM_R, RG_E},
    [0x1E] = {IN_LD, AM_R_D8, RG_E},

    //0x2X
    [0x20] = {IN_JR, AM_D8, RG_NONE, RG_NONE, CND_NZ},
    [0x21] = {IN_LD, AM_R_D16, RG_HL},
    [0x22] = {IN_LD, AM_HLI_R, RG_HL, RG_A},
    [0x23] = {IN_INC, AM_R, RG_HL},
    [0x24] = {IN_INC, AM_R, RG_H},
    [0x25] = {IN_DEC, AM_R, RG_H},
    [0x26] = {IN_LD, AM_R_D8, RG_H},
    [0x28] = {IN_JR, AM_D8, RG_NONE, RG_NONE, CND_Z},
    [0x2A] = {IN_LD, AM_R_HLI, RG_A, RG_HL},
    [0x2B] = {IN_DEC, AM_R, RG_HL},
    [0x2C] = {IN_INC, AM_R, RG_L},
    [0x2D] = {IN_DEC, AM_R, RG_L},
    [0x2E] = {IN_LD, AM_R_D8, RG_L},

    //0x3X
    [0x30] = {IN_JR, AM_D8, RG_NONE, RG_NONE, CND_NC},
    [0x31] = {IN_LD, AM_R_D16, RG_SP},
    [0x32] = {IN_LD, AM_HLD_R, RG_HL, RG_A},
    [0x34] = {IN_INC, AM_MR, RG_HL},
    [0x35] = {IN_DEC, AM_MR, RG_HL},
    [0x36] = {IN_LD, AM_MR_D8, RG_HL},
    [0x38] = {IN_JR, AM_D8, RG_NONE, RG_NONE, CND_C},
    [0x3A] = {IN_LD, AM_R_HLD, RG_A, RG_HL},
    [0x3B] = {IN_DEC, AM_R, RG_SP},
    [0x3C] = {IN_INC, AM_R, RG_A},
    [0x3D] = {IN_DEC, AM_R, RG_A},
    [0x3E] = {IN_LD, AM_R_D8, RG_A},

    //0x4X
    [0x40] = {IN_LD, AM_R_R, RG_B, RG_B},
    [0x41] = {IN_LD, AM_R_R, RG_B, RG_C},
    [0x42] = {IN_LD, AM_R_R, RG_B, RG_D},
    [0x43] = {IN_LD, AM_R_R, RG_B, RG_E},
    [0x44] = {IN_LD, AM_R_R, RG_B, RG_H},
    [0x45] = {IN_LD, AM_R_R, RG_B, RG_L},
    [0x46] = {IN_LD, AM_R_MR, RG_B, RG_HL},
    [0x47] = {IN_LD, AM_R_R, RG_B, RG_A},
    [0x48] = {IN_LD, AM_R_R, RG_C, RG_B},
    [0x49] = {IN_LD, AM_R_R, RG_C, RG_C},
    [0x4A] = {IN_LD, AM_R_R, RG_C, RG_D},
    [0x4B] = {IN_LD, AM_R_R, RG_C, RG_E},
    [0x4C] = {IN_LD, AM_R_R, RG_C, RG_H},
    [0x4D] = {IN_LD, AM_R_R, RG_C, RG_L},
    [0x4E] = {IN_LD, AM_R_MR, RG_C, RG_HL},
    [0x4F] = {IN_LD, AM_R_R, RG_C, RG_A},

    //0x5X
    [0x50] = {IN_LD, AM_R_R,  RG_D, RG_B},
    [0x51] = {IN_LD, AM_R_R,  RG_D, RG_C},
    [0x52] = {IN_LD, AM_R_R,  RG_D, RG_D},
    [0x53] = {IN_LD, AM_R_R,  RG_D, RG_E},
    [0x54] = {IN_LD, AM_R_R,  RG_D, RG_H},
    [0x55] = {IN_LD, AM_R_R,  RG_D, RG_L},
    [0x56] = {IN_LD, AM_R_MR, RG_D, RG_HL},
    [0x57] = {IN_LD, AM_R_R,  RG_D, RG_A},
    [0x58] = {IN_LD, AM_R_R,  RG_E, RG_B},
    [0x59] = {IN_LD, AM_R_R,  RG_E, RG_C},
    [0x5A] = {IN_LD, AM_R_R,  RG_E, RG_D},
    [0x5B] = {IN_LD, AM_R_R,  RG_E, RG_E},
    [0x5C] = {IN_LD, AM_R_R,  RG_E, RG_H},
    [0x5D] = {IN_LD, AM_R_R,  RG_E, RG_L},
    [0x5E] = {IN_LD, AM_R_MR, RG_E, RG_HL},
    [0x5F] = {IN_LD, AM_R_R,  RG_E, RG_A},

    //0x6X
    [0x60] = {IN_LD, AM_R_R,  RG_H, RG_B},
    [0x61] = {IN_LD, AM_R_R,  RG_H, RG_C},
    [0x62] = {IN_LD, AM_R_R,  RG_H, RG_D},
    [0x63] = {IN_LD, AM_R_R,  RG_H, RG_E},
    [0x64] = {IN_LD, AM_R_R,  RG_H, RG_H},
    [0x65] = {IN_LD, AM_R_R,  RG_H, RG_L},
    [0x66] = {IN_LD, AM_R_MR, RG_H, RG_HL},
    [0x67] = {IN_LD, AM_R_R,  RG_H, RG_A},
    [0x68] = {IN_LD, AM_R_R,  RG_L, RG_B},
    [0x69] = {IN_LD, AM_R_R,  RG_L, RG_C},
    [0x6A] = {IN_LD, AM_R_R,  RG_L, RG_D},
    [0x6B] = {IN_LD, AM_R_R,  RG_L, RG_E},
    [0x6C] = {IN_LD, AM_R_R,  RG_L, RG_H},
    [0x6D] = {IN_LD, AM_R_R,  RG_L, RG_L},
    [0x6E] = {IN_LD, AM_R_MR, RG_L, RG_HL},
    [0x6F] = {IN_LD, AM_R_R,  RG_L, RG_A},

    //0x7X
    [0x70] = {IN_LD, AM_MR_R,  RG_HL, RG_B},
    [0x71] = {IN_LD, AM_MR_R,  RG_HL, RG_C},
    [0x72] = {IN_LD, AM_MR_R,  RG_HL, RG_D},
    [0x73] = {IN_LD, AM_MR_R,  RG_HL, RG_E},
    [0x74] = {IN_LD, AM_MR_R,  RG_HL, RG_H},
    [0x75] = {IN_LD, AM_MR_R,  RG_HL, RG_L},
    [0x76] = {IN_HALT},
    [0x77] = {IN_LD, AM_MR_R,  RG_HL, RG_A},
    [0x78] = {IN_LD, AM_R_R,  RG_A, RG_B},
    [0x79] = {IN_LD, AM_R_R,  RG_A, RG_C},
    [0x7A] = {IN_LD, AM_R_R,  RG_A, RG_D},
    [0x7B] = {IN_LD, AM_R_R,  RG_A, RG_E},
    [0x7C] = {IN_LD, AM_R_R,  RG_A, RG_H},
    [0x7D] = {IN_LD, AM_R_R,  RG_A, RG_L},
    [0x7E] = {IN_LD, AM_R_MR, RG_A, RG_HL},
    [0x7F] = {IN_LD, AM_R_R,  RG_A, RG_A},

    //0x8X
    [0x80] = {IN_ADD, AM_R_R, RG_A, RG_B},
    [0x81] = {IN_ADD, AM_R_R, RG_A, RG_C},
    [0x82] = {IN_ADD, AM_R_R, RG_A, RG_D},
    [0x83] = {IN_ADD, AM_R_R, RG_A, RG_E},
    [0x84] = {IN_ADD, AM_R_R, RG_A, RG_H},
    [0x85] = {IN_ADD, AM_R_R, RG_A, RG_L},
    [0x86] = {IN_ADD, AM_R_MR, RG_A, RG_HL},
    [0x87] = {IN_ADD, AM_R_R, RG_A, RG_A},
    [0x88] = {IN_ADC, AM_R_R, RG_A, RG_B},
    [0x89] = {IN_ADC, AM_R_R, RG_A, RG_C},
    [0x8A] = {IN_ADC, AM_R_R, RG_A, RG_D},
    [0x8B] = {IN_ADC, AM_R_R, RG_A, RG_E},
    [0x8C] = {IN_ADC, AM_R_R, RG_A, RG_H},
    [0x8D] = {IN_ADC, AM_R_R, RG_A, RG_L},
    [0x8E] = {IN_ADC, AM_R_MR, RG_A, RG_HL},
    [0x8F] = {IN_ADC, AM_R_R, RG_A, RG_A},

    //0x9X
    [0x90] = {IN_SUB, AM_R_R, RG_A, RG_B},
    [0x91] = {IN_SUB, AM_R_R, RG_A, RG_C},
    [0x92] = {IN_SUB, AM_R_R, RG_A, RG_D},
    [0x93] = {IN_SUB, AM_R_R, RG_A, RG_E},
    [0x94] = {IN_SUB, AM_R_R, RG_A, RG_H},
    [0x95] = {IN_SUB, AM_R_R, RG_A, RG_L},
    [0x96] = {IN_SUB, AM_R_MR, RG_A, RG_HL},
    [0x97] = {IN_SUB, AM_R_R, RG_A, RG_A},
    [0x98] = {IN_SBC, AM_R_R, RG_A, RG_B},
    [0x99] = {IN_SBC, AM_R_R, RG_A, RG_C},
    [0x9A] = {IN_SBC, AM_R_R, RG_A, RG_D},
    [0x9B] = {IN_SBC, AM_R_R, RG_A, RG_E},
    [0x9C] = {IN_SBC, AM_R_R, RG_A, RG_H},
    [0x9D] = {IN_SBC, AM_R_R, RG_A, RG_L},
    [0x9E] = {IN_SBC, AM_R_MR, RG_A, RG_HL},
    [0x9F] = {IN_SBC, AM_R_R, RG_A, RG_A},

    //OxAX
    [0xAF] = {IN_XOR, AM_R, RG_A},

    //0xCX
    [0xC0] = {IN_RET, AM_IMP, RG_NONE, RG_NONE, CND_NZ},
    [0xC1] = {IN_POP, AM_IMP, RG_BC},
    [0xC2] = {IN_JP, AM_D16, RG_NONE, RG_NONE, CND_NZ},
    [0xC3] = {IN_JP, AM_D16},
    [0xC4] = {IN_CALL, AM_D16, RG_NONE, RG_NONE, CND_NZ},
    [0xC5] = {IN_PUSH, AM_IMP, RG_BC},
    [0xC6] = {IN_ADD, AM_R_D8, RG_A},
    [0xC7] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x00},
    [0XC8] = {IN_RET, AM_IMP, RG_NONE, RG_NONE, CND_Z},
    [0XC9] = {IN_RET},
    [0xCA] = {IN_JP, AM_D16, RG_NONE, RG_NONE, CND_Z},
    [0xCC] = {IN_CALL, AM_D16, RG_NONE, RG_NONE, CND_Z},
    [0xCD] = {IN_CALL, AM_D16},
    [0xCE] = {IN_ADC, AM_R_D8, RG_A},
    [0xCF] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x08},

    //0xD0
    [0XD0] = {IN_RET, AM_IMP, RG_NONE, RG_NONE, CND_NC},
    [0xD1] = {IN_POP, AM_IMP, RG_DE},
    [0xD2] = {IN_JP, AM_D16, RG_NONE, RG_NONE, CND_NC},
    [0xD4] = {IN_CALL, AM_D16, RG_NONE, RG_NONE, CND_NC},
    [0xD5] = {IN_PUSH, AM_IMP, RG_DE},
    [0xD6] = {IN_SUB, AM_R_D8, RG_A},
    [0xD7] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x10},
    [0XD8] = {IN_RET, AM_IMP, RG_NONE, RG_NONE, CND_C},
    [0XD9] = {IN_RETI},
    [0xDA] = {IN_JP, AM_D16, RG_NONE, RG_NONE, CND_C},
    [0xDC] = {IN_CALL, AM_D16, RG_NONE, RG_NONE, CND_C},
    [0xDE] = {IN_SBC, AM_R_D8, RG_A},
    [0xDF] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x18},
    

    //0xEX
    [0xE0] = {IN_LDH, AM_A8_R, RG_NONE,  RG_A},
    [0xE1] = {IN_POP, AM_IMP, RG_HL},
    [0xE2] = {IN_LD, AM_MR_R, RG_C, RG_A},
    [0xE5] = {IN_PUSH, AM_IMP, RG_HL},
    [0xE7] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x20},
    [0xE9] = {IN_JP, AM_MR, RG_HL},
    [0xEA] = {IN_LD, AM_A16_R, RG_NONE, RG_A},
    [0xEF] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x28},


    //0xFX
    [0xF0] = {IN_LDH, AM_R_A8, RG_A, RG_NONE},
    [0xF1] = {IN_POP, AM_IMP, RG_AF},
    [0xF2] = {IN_LD, AM_R_MR, RG_A, RG_C},
    [0xF3] = {IN_DI},
    [0xF5] = {IN_PUSH, AM_IMP, RG_AF},
    [0xF7] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x30},
    [0xFA] = {IN_LD, AM_R_A16, RG_A},
    [0xFF] = {IN_RST, AM_IMP, RG_NONE, RG_NONE, CND_NONE, 0x38},
};

instruction *instruction_by_opcode(u8 opcode) {
    return &instructions[opcode];
}

char *inst_lookup[] = {
    "<NONE>",
    "NOP",
    "LD",
    "INC",
    "DEC",
    "RLCA",
    "ADD",
    "RRCA",
    "STOP",
    "RLA",
    "JR",
    "RRA",
    "DAA",
    "CPL",
    "SCF",
    "CCF",
    "HALT",
    "ADC",
    "SUB",
    "SBC",
    "AND",
    "XOR",
    "OR",
    "CP",
    "POP",
    "JP",
    "PUSH",
    "RET",
    "CB",
    "CALL",
    "RETI",
    "LDH",
    "JPHL",
    "DI",
    "EI",
    "RST",
    "IN_ERR",
    "IN_RLC", 
    "IN_RRC",
    "IN_RL", 
    "IN_RR",
    "IN_SLA", 
    "IN_SRA",
    "IN_SWAP", 
    "IN_SRL",
    "IN_BIT", 
    "IN_RES", 
    "IN_SET"
};

char *inst_name(inType t) {
    return inst_lookup[t];
}